baseURL = "https://www.qualitycoders.be"
languageCode = "nl-BE"
title = "Quality Coders"
paginate = 8
theme = "photon"
hasCJKLanguage=true

[permalinks]
    nieuws = "/:section/:year/:month/:day/:slug/"

[params]
dateForm = "January 2, 2006"


# Variables for out of site navigation

[[params.social]]
    icon = "fa-twitter"
    name = "Twitter"
	url = "https://twitter.com/qualitycoders"
    weight = 5

[[params.social]]
    icon = "fa-linkedin"
    name = "Linkedin"
	url = "https://www.linkedin.com/in/kimlauwers/"
    weight = 6

[[params.social]]
    icon = "fa-github"
    name = "Github"
	url = "https://github.com/Kim-Lauwers"
    weight = 7

[[params.social]]
    icon = "fa-lock"
    name = "Keybase"
	url = "https://keybase.io/kimlauwers"
    weight = 8

[[params.social]]
    icon = "fa-envelope"
    name = "Email"
	url = "mailto:info@qualitycoders.be"
    weight = 10