baseURL = "https://www.qualitycoders.be"
languageCode = "nl-BE"
title = "Quality Coders"
paginate = 8
theme = "photon"
hasCJKLanguage=true

[permalinks]
    nieuws = "/:section/:year/:month/:day/:slug/"

[params]
dateForm = "January 2, 2006"


# Variables for out of site navigation

[[params.social]]
	icon = "fa-facebook"
    name = "Facebook"
	url = "https://www.facebook.com/groups/357231384348318/"
    weight = 1

[[params.social]]
    icon = "fa-twitter"
    name = "Twitter"
	url = "https://twitter.com/qualitycoders"
    weight = 5

[[params.social]]
    icon = "fa-mail-forward"
    name = "Email"
	url = "mailto:info@qualitycoders.be"
    weight = 10